export const persion = {
  ASAN_BOURSE: "آسان بورس",
  INDEX: "فهرست",
  INDICATORS: "اندیکاتور",
  WARRANTS: "حق تقدم",
  FINANCIAL_RELATIONS: "نسبت های مالی",
  DPS: "سود تقسیمی",
  DASHBOARD: "داشبورد",
  DATX: "داده پردازان تدبیر سرمایه",
  VERSION: "ورژن",
  INSTRUMENT:"عنوان نماد",
  INSTRUMENT_EN:"عنوان نماد انگلیسی",
  NAME:"نام",
  NAME_EN:"نام انگلیسی",
  ISSUER_CLASS:"کلاس صادرکننده",
  TYPE1:"نوع یک",
  TYPE2:"نوع دو",
  CURRENCY:"واحد",
  NUM_OF_PAYMENTS:"تعداد پرداختی",
  EMISSION_VOLUME:"حجم",
  PARVALUE:"ارزش هر سهم",
  COUPONRATE:"نرخ کوپن",
  ISSUE_DATE:"تاریخ صدور",
  MATURITYDAY:"زمان سررسید",
  ACCRUAL_START_DATE:"زمان شروع سررسید",
  ISIN:"شناسه نماد",
  LAST_MODIFY_DATE:"تاریخ آخرین ویرایش",
  ROW:"ردیف",
  ITEM:"آیتم",
  VSLUE:"مقدار",
  DATE:"تاریخ",
  FISCAL_YEAR:"سال مالی",
  FISCAL_MONTH:"ماه مالی",
  CAPITAL_INCREASE:"افزایش سرمایه",
  CAPITAL_CHANGE_PERCENT:"درصد تغییر سرمایه",
  CONTRIBUTION_PERCENT:"درصد سهم",
  NEW_CAOITAL:"سهم جدید",
  PREMIUM_PERCENT:"درصد حق بیمه",
  PREVIUS_CAPITAL:"سرمایه قبلی",
  RESERVE_PERCENT:"درصد ذخیره",
  BONDS:"اطلاعات اوراق",
  WARNING:"هشدار",
  UPDATE_INTERVALS:"فواصل زمانی بروزرسانی",
};
